### ISSUE TITLE
Try to use cancel on time instead of three.

### ISSUE THREAD

**Issue by SashaMikhailau** [yury-raichonok/myproject-aem#1]
https://github.com/yury-raichonok/myproject-aem/blob/5cc6e5c84c65d8e29d87c19b6b12e042f675032b/core/src/main/java/com/myproject/core/jobs/impl/PropertyRemovalJobConsumer.java#L59

**Comment by yury-raichonok** [comment]
Code refactored. 'Cancel' status now return only in one place
